services:
  vision-fr-postgres:
    container_name: vision-fr-postgres
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    networks:
      - vision-fr-network

networks:
  vision-fr-network:
    name: vision-fr-network
    driver: bridge